FROM node:22-alpine3.19

WORKDIR /react/cash-web 

COPY package*.json ./

RUN npm install 

RUN npm install prisma
RUN npm install @prisma/client
RUN npm install express
#RUN npx prisma migrate dev --name init
#RUN npx prisma generate

#CMD ["npm", "start"]
#ENTRYPOINT ["/bin/sh"]
CMD ["./start-up.sh"]
# Wait forever
#CMD ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]