FROM node:22-alpine3.19

WORKDIR /react/cash-web 

COPY package*.json ./

RUN npm install 

#CMD ["npm", "start"]
#ENTRYPOINT ["/bin/sh"]
#CMD ["./start-up.sh"]
# Wait forever
CMD ["sh", "-c", "trap : TERM INT; sleep infinity & wait"]