version: '3'
services:
  cash-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cash_register_100!
      MYSQL_DATABASE: cash_register_db

  cash-web:
    build: cash-web
    volumes:      
      - ./cash-web:/react/cash-web
      - /react/cash-web/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - cash-db
      

